version: '2'
services:
  express:
    volumes: ['apps']
    restart: 'always'
    container_name: 'disney_reservation_event_maker_server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3008:3008'
